#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash =
    await import(
      "libcrash-js");
/* global
     _argv */
const
  _argv =
    _libcrash._argv;
/* global
     _basename */
const
  _basename =
    _libcrash._basename;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _file_read */
const
  _file_read =
    _libcrash._file_read;
/* global
     _file_write */
const
  _file_write =
    _libcrash._file_write;
/* global
     _get */
const
  _get =
    _libcrash._get;
/* global
     _global_get */
const
  _global_get =
    _libcrash._global_get;
/* global
     _json_display */
const
  _json_display =
    _libcrash._json_display;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
_msg_error =
  _libcrash._msg_error;
/* global
     _override_set */
const
  _override_set =
    _libcrash._override_set;
/* global
     _require */
const
  _require =
    _libcrash._require;
/* global
     _set */
const
  _set =
    _libcrash._set;
const
  _ethers_module =
    await _require(
      "ethers");
/* global
     _ethers */
const
  _ethers =
    _ethers_module.ethers;
/* global
     _wei_to_ether */
const
  _wei_to_ether =
    _ethers.formatEther;
/* global
     _parse_units */
const
  _parse_units =
    _ethers.parseUnits;
const
  _evm_contracts_tools_module =
    await import(
      "evm-contracts-tools");
/* global
     _contract_run */
_contract_run =
  _evm_contracts_tools_module._contract_run;
const
  _erc20_contracts_module =
    await _require(
      "erc20-contracts");
/* global
     _data_get */
_data_get =
  _erc20_contracts_module._data_get;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  _set(
    "app",
    "name",
    "token-send");
  /* global
       retries_max:
         writable */
  _set(
    "retries",
    "max",
    "");
  /* global
       call_timeout:
         writable */
  _set(
    "call",
    "timeout",
    "");
  /* global
       wallet_seed_path:
         writable */
  _set(
    "wallet_seed",
    "path",
    "");
  /* global
       api_key_path:
         writable */
  _set(
    "api_key",
    "path",
    "");
  /* global
       target_network:
         writable */
  _set(
    "target",
    "network",
    "");
  /* global
       token_address:
         writable */
  _set(
    "token",
    "address",
    "");
  /* global
       token_abi_path:
         writable */
  _set(
    "token_abi",
    "path",
    "");
  /* global
       token_bytecode_path:
         writable */
  _set(
    "token_bytecode",
    "path",
    "");
  /* global
       token_compiler_output_path:
         writable */
  _set(
    "token_compiler_output",
    "path",
    "");
  /* global
       measure_unit:
         writable */
  _set(
    "measure",
    "unit",
    "");
  /* global
       target_recipient:
         writable */
  _set(
    "target",
    "recipient",
    "");
  /* global
       target_amount:
         writable */
  _set(
    "target",
    "amount",
    "");
  /* global
       receipt_file_path:
         writable */
  _set(
    "receipt_file",
    "path",
    "");
  const
    _global =
      _global_get();
  /* global
       quiet:
         writable */
  _global[
    "quiet"] =
    "";
}

async function
  _token_send_call(
    _contract_run_opts) {
  let
    _tx;
  try {
    _tx = await
      _contract_run.apply(
        null,
        _contract_run_opts);
  } catch(
      _error) {
    const
      _msg =
        "Error sending the amount.";
    _error_display(
      _error);
    _msg_error(
      _msg,
      0);
    throw _error;
  }
  return _tx;
}

function
  _ether_to_wei(
    _amount) {
  return _parse_units(
    _amount,
    "ether");
}

async function
  _token_send(
    _retries_max,
    _call_timeout,
    _wallet_seed_path,
    _api_key_path,
    _target_network,
    _token_address,
    _token_abi_path,
    _token_bytecode_path,
    _token_compiler_output_path,
    _measure_unit,
    _receipt_file_path,
    _target_recipient,
    _amount
  ) {
  let
    _msg,
    _receipt,
    _receipt_json,
    _token_send_call_base_opts,
    _token_send_call_opts,
    _transfer_args,
    _wallet_password;
  if ( typeof(
         _token_abi_path) == "undefined" ||
       _token_abi_path == "" ) {
    _token_abi_path =
      _data_get(
        "Token",
        "abi",
        "path");
  }
  if ( typeof(
         _token_bytecode_path) == "undefined" ||
       _token_bytecode_path == "" ) {
    _token_bytecode_path =
      _data_get(
        "Token",
        "bytecode",
        "path");
  }
  if ( typeof(
         _token_compiler_output_path) == "undefined" ||
       _token_compiler_output_path == "" ) {
    _token_compiler_output_path =
      _data_get(
        "Token",
        "compiler-output",
        "path");
  }
  if ( typeof(
         _amount) == "undefined" ||
       _amount == "" ) {
    _msg =
      "Amount must be a number greater than zero.";
    _msg_error(
      _msg,
      1);
  }
  if ( _receipt_file_path == undefined ) {
    _receipt_file_path =
      "";
  }
  if ( _call_timeout == "" ) {
    _call_timeout =
      300000;
  }
  _call_timeout =
    Number(
      _call_timeout);
 if ( _measure_unit == "ether" ) {
    _amount =
      _ether_to_wei(
        _amount);
  }
  _amount =
    BigInt(
      _amount);
  _wallet_password =
    "";
  _token_send_call_base_opts = [
    _retries_max,
    _call_timeout,
    _wallet_seed_path,
    _wallet_password,
    _api_key_path,
    "",
    0,
    "ether",
    _target_network,
    _token_address,
    _token_abi_path,
    _token_bytecode_path,
    _token_compiler_output_path,
    "transfer"
  ];
  _transfer_args = [
    _target_recipient,
    _amount
  ];
  _token_send_call_opts =
    _token_send_call_base_opts.concat(
      [ _transfer_args ]);
  try {
    _receipt = await
      _token_send_call(
        _token_send_call_opts);
  } catch (
      _error) {
    _error_display(
      _error);
    _msg =
      "Error sending the intended token amount.";
    _msg_error(
      _msg,
      0);
    throw _error;
  }
  if ( _receipt_file_path != "" ) {
    _receipt_json =
      _json_display(
        _receipt);
    _file_write(
      _receipt_file_path,
      _receipt_json);
  }
  return _receipt;
}

function
  _config_show() {
  let
    _line;
  const
    _program =
      _basename(
        _argv[
          "1"]);
  const
    _text = [
    `          Maximum retries: ${retries_max}`,
    `             Call timeout: ${call_timeout}`,
    `              Wallet seed: ${wallet_seed_path}`,
    `                  API Key: ${api_key_path}`,
    `           Target network: ${target_network}`,
    `            Token address: ${token_address}`,
    `                Token ABI: ${token_abi_path}`,
    `           Token bytecode: ${token_bytecode_path}`,
    `    Token compiler output: ${token_compiler_output_path}`,
    `             Measure unit: ${measure_unit}`,
    `        Receipt file path: ${receipt_file_path}`,
    `         Target recipient: ${target_recipient}`,
    `            Target amount: ${target_amount}`,
    ];
  for ( _line in _text ) {
    _msg_info(
      _text[
        _line]);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line,
    _text;
  if ( typeof(
         _exit_code) == "undefined" ||
       _exit_code == "" ) {
    _exit_code =
      0;
  }
  const
    _program =
      _basename(
        _argv[
          "1"]);
  _text = [
    "Send ERC-20 tokens.",
    "",
    "Usage:",
    `  ${_program}`,
    "    <quiet>",
    "    <retries-max>",
    "    <call-timeout>",
    "    <wallet-seed-path>",
    "    <api-key-path>",
    "    <target-network>",
    "    <token-address>",
    "    <token-abi-path>",
    "    <token-bytecode-path>",
    "    <token-compiler-output-path>",
    "    <measure-unit>",
    "    <receipt-file-path>",
    "    <target-recipient>",
    "    <target-amount>",
    "",
    "Args:",
    "",
    "  <quiet>                          Can be 'y' or 'n'",
    `                                   Default: ${quiet}`,
    "",
    "  <retries-max>                    Maximum number of retries before",
    "                                   failing.",
    `                                   Default: ${retries_max}`,
    "",
    "  <call-timeout>                   How many milliseconds to wait for a return",
    "                                   before declaring the call failed.",
    `                                   Default: ${call_timeout}`,
    "",
    "  <wallet-seed-path>               Path of the file containing",
    "                                   the seed phrase.",
    `                                   Default: ${wallet_seed_path}`,
    "",
    "  <api-key-path>                   Path of the API key for the",
    "                                   contract ABI provider service.",
    "",
    "  <target-network>                 Network on which the contract",
    "                                   resides.",
    "",
    "  <token-address>                  Address of the token contract.",
    "",
    "  <token-abi-path>                 Token ABI path.",
    `                                   Default: ${token_abi_path}`,
    "",
    "  <token-bytecode-path>            Path for the token bytecode.",
    `                                   Default: ${token_bytecode_path}`,
    "",
    "  <token-compiler-output-path>     Path for the token compiler",
    "                                   output path (the hardhat artifact).",
    `                                   Default: ${token_compiler_output_path}`,
    "",
    "  <measure-unit>                   Measure unit for the transaction",
    "                                   value. It can be 'wei' or 'ether'",
    `                                   Default: ${measure_unit}`,
    "",
    "  <receipt-file-path>              If specified, will save the transaction",
    "                                   receipt at the path.",
    "",
    `  <target-amount>                  How much '${measure_unit}' of the specified`,
    "                                   token to send.",
  ];
  for ( _line of _text ) {
    console.log(
      _line);
  }
  process.exit(
    _exit_code);
}

async function 
  _cmdline_parse() {
  let
    _msg;
  const
    _global =
      _global_get();
  _global[
    "quiet"] =
    "y";
  _argv.forEach(
    function (
      _value,
      _index) {
      if ( _index == 2 ) {
        _global[
          "quiet"] =
          _value;
      }
      if ( _index == 3 ) {
        _set(
          "retries",
          "max",
          _value);
      }
      if ( _index == 4 ) {
        _set(
          "call",
          "timeout",
          _value);
      }
      if ( _index == 5 ) {
        _set(
          "wallet_seed",
          "path",
          _value);
      }
      if ( _index == 6 ) {
        _set(
          "api_key",
          "path",
          _value);
      }
      if ( _index == 7 ) {
        _set(
          "target",
          "network",
          _value);
      }
      if ( _index == 8 ) {
        _set(
          "token",
          "address",
          _value);
      }
      if ( _index == 9 ) {
        _set(
          "token_abi",
          "path",
          _value);
      }
      if ( _index == 10 ) {
        _set(
          "token_bytecode",
          "path",
          _value);
      }
      if ( _index == 11 ) {
        _set(
          "token_compiler_output",
          "path",
          _value);
      }
      if ( _index == 12 ) {
        _set(
          "measure",
          "unit",
          _value);
      }
      if ( _index == 13 ) {
        _set(
          "receipt_file",
          "path",
          _value);
      }
      if ( _index == 14 ) {
        _set(
          "target",
          "recipient",
          _value);
      }
      if ( _index == 15 ) {
        _set(
          "target",
          "amount",
          _value);
      }
      if ( _value == "-h" ||
           _value == "--help" ) {
        await _overrides_set();
        _global[
          "quiet"] =
          "n";
        _usage(
          0);
      }
  });
  if ( target_recipient == "" ) {
    await _overrides_set();
    _global[
      "quiet"] =
      "n";
    _msg =
       "No input recipient.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
  if ( token_address == "" ) {
    await _overrides_set();
    _global[
      "quiet"] =
      "n";
    _msg =
       "No token address specified.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
  if ( target_amount == "" ) {
    _global[
      "quiet"] =
      "n";
    _msg =
       "No amount specified.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
  if ( target_amount == "0" ||
       target_amount == 0 ) {
    await _overrides_set();
    _global[
      "quiet"] =
      "n";
    _msg =
       "Amount specified is zero.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
}

async function
  _token_send_cmdline(
    _app_opts) {
  let
    _msg,
    _receipt;
  try {
    _receipt =
      await _token_send.apply(
        null,
        _app_opts);
    if (  _receipt == undefined ) {
      _msg =
        "Error sending the amount.";
      throw { "error": {
                "message":
                  _msg} };
    }
    console.log(
      _receipt);
  } catch (
      _error) {
    _msg =
      "Transfer error.";
    _error_display(
      _error);
    _msg_error(
      _msg,
      1);
  }
}

async function
  _overrides_set() {
  let
    _info_get,
    _target_network_type;
  _info_get =
    false;
  const
    _target_network =
      _get(
        "target",
        "network");
  _target_network_type =
    typeof(
      _target_network);
  if ( _target_network_type == "undefined" ||
       _target_network == "" ) {
    _target_network = 100;
    _target_network_type =
      typeof(
        _target_network);
  }
  if ( _target_network_type == "number" ) {
    _info_get =
      true;
  }
  else if ( _target_network_type == "string" ) {
    if ( ! _target_network.startsWith(
           "https://") ) {
      _info_get =
        true;
    }
  }
  else {
    const
      _msg =
        `Unknown type '${_target_network_type}' ` +
        `for network variable.`;
    throw _msg;
  }
  if ( _info_get ) {
    const
      _libevm_module =
        await import(
          "libevm");
    const
      _rpc_get =
        _libevm_module._rpc_get;
    _target_network =
      _rpc_get(
        [ target_network ])[
        target_network];
  }
  _set(
    "target",
    "network",
    _target_network);
  _override_set(
    "token_abi",
    "path",
    _data_get(
      "Token",
      "abi",
      "path"));
  _override_set(
    "token_bytecode",
    "path",
    _data_get(
      "Token",
      "bytecode",
      "path"));
  _override_set(
    "token_compiler_output",
    "path",
    _data_get(
      "Token",
      "compiler_output",
      "path"));
  _override_set(
    "call",
    "timeout",
    300000);
  _override_set(
    "measure",
    "unit",
    "ether");
}

if ( await _cmdline_check(
       "token-send") ||
     await _cmdline_check(
       "erc20-token-send") ) {
  _global_variables();
  await _cmdline_parse();
  await _overrides_set();
  _config_show();
  app_opts = [
    retries_max,
    call_timeout,
    wallet_seed_path,
    api_key_path,
    target_network,
    token_address,
    token_abi_path,
    token_bytecode_path,
    token_compiler_output_path,
    measure_unit,
    receipt_file_path,
    target_recipient,
    target_amount,
  ];
  _token_send_cmdline(
    app_opts);
}

export {
  _token_send
};

// module.exports = {
//   _token_send:
//     _token_send
// };
